# @package _global_
# configs/launcher/super_gpu_normal.yaml

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 10
    mem_gb: 400
    partition: gpu_p
    qos: gpu_normal
    gres: gpu:1
    timeout_min: 1440
    constraint: h100_80gb