adata_path: "/lustre/groups/ml01/workspace/alessandro.palma/celldreamer/datasets/processed_full_genome/c_elegans/c_elegans.h5ad"
output_dir: "/home/icb/lorenzo.consoli/repos/scFM_density_estimation/dumps"
