n_hidden: 128
n_latent: 10
n_layers: 1
dropout_rate: 0.1
dispersion: "gene"
gene_likelihood: "zinb"
use_observed_lib_size: True
latent_distribution: "normal"
log_variational: True
encode_covariates: False
deeply_inject_covariates: True
batch_representation: "one-hot"
use_batch_norm: "both"
use_layer_norm: "none"
use_size_factor_key: False
extra_payload_autotune: False
extra_encoder_kwargs: null
extra_decoder_kwargs: null
